// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQChQAlOrgKtxgg9Dun4FM52hbpFled2k',
    appId: '1:844517950047:web:535c723a85a501754551ea',
    messagingSenderId: '844517950047',
    projectId: 'esp32-watergsc',
    authDomain: 'esp32-watergsc.firebaseapp.com',
    databaseURL:
        'https://esp32-watergsc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-watergsc.appspot.com',
    measurementId: 'G-SVKRYT9Z5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO72Fp-UYjS05Z0WeLPboL20ztsgBz9Fw',
    appId: '1:844517950047:android:454c74eaa901bad54551ea',
    messagingSenderId: '844517950047',
    projectId: 'esp32-watergsc',
    databaseURL:
        'https://esp32-watergsc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-watergsc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjQ_9vyueBAFTtax76LtS_tOfA6rUdOpE',
    appId: '1:844517950047:ios:6c15b222d1e133af4551ea',
    messagingSenderId: '844517950047',
    projectId: 'esp32-watergsc',
    databaseURL:
        'https://esp32-watergsc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-watergsc.appspot.com',
    iosBundleId: 'com.example.gsc2024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjQ_9vyueBAFTtax76LtS_tOfA6rUdOpE',
    appId: '1:844517950047:ios:7408026575f867f04551ea',
    messagingSenderId: '844517950047',
    projectId: 'esp32-watergsc',
    databaseURL:
        'https://esp32-watergsc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-watergsc.appspot.com',
    iosBundleId: 'com.example.gsc2024.RunnerTests',
  );
}
